#lang racket

(require rackunit)
(require "../joker.rkt")

(check-equal? (best-total '()) 0)
(check-equal? (best-total '(2C)) 2)
(check-equal? (best-total '(2C 4D)) 6)
(check-equal? (best-total '(2C 10H 7C)) 19)

(check-equal? (best-total '(10D 6C AD RR)) 21)
(check-equal? (best-total '(10D 6C AD)) 17)
(check-equal? (best-total '(10D 10C AD)) 21)
(check-equal? (best-total '(10D 10C RR)) 21)
(check-equal? (best-total '(10D 10C)) 20)

(check-equal? (best-total '(RR)) 11)
(check-equal? (best-total '(RR RR)) 21)
(check-equal? (best-total '(AD)) 11)
(check-equal? (best-total '(AD RR)) 21)
(check-equal? (best-total '(AD AS RR)) 21)
(check-equal? (best-total '(AD AS AH)) 13)
(check-equal? (best-total '(AD AS AH RR)) 21)
(check-equal? (best-total '(AD AS AH AC)) 14)
(check-equal? (best-total '(AD AS AH AC RR)) 21)
(check-equal? (best-total '(AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(3C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 2C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 3C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 4C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 5C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 6C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 7C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 8C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 9C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(2C 10C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(3C 10C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(4C 10C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(5C 10C AD AS AH AC RR RR)) 21)
(check-equal? (best-total '(6C 10C AD AS AH AC RR RR)) 22)
(check-equal? (best-total '(7C 10C AD AS AH AC RR RR)) 23)
(check-equal? (best-total '(2H 7C 10C AD AS AH AC RR RR)) 25)
